"""bd

Revision ID: 4eb3593b4f28
Revises: 0085f14aa2f0
Create Date: 2023-01-17 11:37:29.926699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb3593b4f28'
down_revision = '0085f14aa2f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
