"""bd2

Revision ID: 528d13f7cd55
Revises: 4eb3593b4f28
Create Date: 2023-01-17 13:08:20.824981

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '528d13f7cd55'
down_revision = '4eb3593b4f28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Dish_title_key', 'Dish', type_='unique')
    op.drop_constraint('Menu_title_key', 'Menu', type_='unique')
    op.drop_constraint('Submenu_title_key', 'Submenu', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Submenu_title_key', 'Submenu', ['title'])
    op.create_unique_constraint('Menu_title_key', 'Menu', ['title'])
    op.create_unique_constraint('Dish_title_key', 'Dish', ['title'])
    # ### end Alembic commands ###
