"""3

Revision ID: 65f0eaf54241
Revises: b824eb9ada73
Create Date: 2023-01-16 13:46:13.375369

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '65f0eaf54241'
down_revision = 'b824eb9ada73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
