"""4th

Revision ID: 6abbcd1d6744
Revises: 65f0eaf54241
Create Date: 2023-01-16 16:13:00.209143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6abbcd1d6744'
down_revision = '65f0eaf54241'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Dish', sa.Column('submenu_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_Dish_submenu_id'), 'Dish', ['submenu_id'], unique=False)
    op.create_foreign_key(None, 'Dish', 'Submenu', ['submenu_id'], ['id'])
    op.drop_constraint('Menu_submenu_fkey', 'Menu', type_='foreignkey')
    op.drop_column('Menu', 'submenu')
    op.add_column('Submenu', sa.Column('menu_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_Submenu_menu_id'), 'Submenu', ['menu_id'], unique=False)
    op.drop_constraint('Submenu_dish_fkey', 'Submenu', type_='foreignkey')
    op.create_foreign_key(None, 'Submenu', 'Menu', ['menu_id'], ['id'])
    op.drop_column('Submenu', 'dish')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Submenu', sa.Column('dish', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Submenu', type_='foreignkey')
    op.create_foreign_key('Submenu_dish_fkey', 'Submenu', 'Dish', ['dish'], ['id'])
    op.drop_index(op.f('ix_Submenu_menu_id'), table_name='Submenu')
    op.drop_column('Submenu', 'menu_id')
    op.add_column('Menu', sa.Column('submenu', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Menu_submenu_fkey', 'Menu', 'Submenu', ['submenu'], ['id'])
    op.drop_constraint(None, 'Dish', type_='foreignkey')
    op.drop_index(op.f('ix_Dish_submenu_id'), table_name='Dish')
    op.drop_column('Dish', 'submenu_id')
    # ### end Alembic commands ###
