"""bd3

Revision ID: 72fd67344373
Revises: 528d13f7cd55
Create Date: 2023-01-17 13:22:35.195323

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '72fd67344373'
down_revision = '528d13f7cd55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
